#!/bin/sh
#
#
###  ==============================
# :FILE-CREATED <Timestamp: #{2011-04-20T12:58:07-04:00Z}#{11163} - by MON>
# :FILE dbc-specific/make-dbc-specific-etags
#
#  Add the current directory to the tail of Emacs' `tags-table-list'
# (add-to-list 'tags-table-list default-directory t)
#
# Make sure to tell customize or it'll wind up bitching:
# (custom-note-var-changed 'tags-table-list)
# 
# Currently not tagging these:
# ./dbc-time/dbc-parse-time.lisp \
# ./dbc-time/date-calc.lisp \
#
###  ==============================

etags ./specials.lisp \
./package.lisp \
./conditions.lisp \
./loadtime-bind.lisp \
./dbc-utils.lisp \
./dbc-classes/dbc-class.lisp \
./dbc-classes/dbc-class-paths.lisp \
./dbc-classes/dbc-class-uuid.lisp \
./dbc-classes/dbc-class-system-object-uuid.lisp \
./dbc-classes/dbc-class-uuid-vars.lisp \
./dbc-classes/dbc-class-record.lisp \
./dbc-classes/dbc-class-inventory-record.lisp \
./dbc-classes/dbc-class-inventory-publication-record.lisp \
./dbc-classes/dbc-class-inventory-sales-record.lisp \
./dbc-classes/dbc-class-authority-record.lisp \
./dbc-classes/dbc-class-entity.lisp \
./dbc-classes/dbc-class-control-id.lisp \
./dbc-classes/dbc-class-edit.lisp \
./dbc-classes/dbc-class-naf-entity.lisp \
./dbc-classes/dbc-class-theme-entity.lisp \
./dbc-classes/dbc-class-media-entity.lisp \
./dbc-classes/dbc-class-location-entity.lisp \
./dbc-classes/dbc-class-taxon-entity.lisp \
./dbc-classes/dbc-class-regexps.lisp \
./dbc-classes/dbc-class-users.lisp \
./dbc-classes/dbc-class-description.lisp \
./dbc-classes/dbc-class-documentation-record.lisp \
./dbc-classes/dbc-class-parsed.lisp \
./dbc-classes/dbc-class-parsed-slot-value-equal.lisp \
./dbc-classes/dbc-class-parsed-field-slot-mapping.lisp \
./dbc-classes/dbc-class-parsed-convert.lisp \
./dbc-classes/dbc-class-parsed-slot-value-format.lisp \
./dbc-classes/dbc-class-parsed-inventory-record.lisp \
./dbc-classes/dbc-class-parsed-artist-record.lisp \
./dbc-classes/dbc-class-parsed-author-record.lisp \
./dbc-classes/dbc-class-parsed-person-record.lisp \
./dbc-classes/dbc-class-parsed-brand-record.lisp \
./dbc-classes/dbc-class-parsed-technique-record.lisp \
./dbc-classes/dbc-class-parsed-publication-record.lisp \
./dbc-classes/dbc-class-parsed-theme-record.lisp \
./dbc-classes/dbc-class-parsed-documentation-record.lisp \
./dbc-classes/dbc-class-parsed-translation-for-inventory-record.lisp \
./dbc-classes/dbc-class-parsed-inventory-sales-order-record.lisp \
./dbc-classes/dbc-class-parsed-inventory-sales-sold-record.lisp \
./dbc-classes/dbc-class-parsed-inventory-sales-sold-in-store-record.lisp \
./dbc-classes/dbc-class-image.lisp \
./dbc-classes/dbc-class-image-path-convert.lisp \
./dbc-classes/dbc-class-image-path-inventory-record.lisp \
./dbc-classes/dbc-class-parsed-csv-writer.lisp \
./dbc-classes/dbc-class-parsed-slot-value-cleaning.lisp \
./dbc-classes/dbc-tgm.lisp \
./dbc-classes/dbc-class-category-entities/dbc-class-category-entity.lisp \
./dbc-parse/dbc-cln-parse.lisp \
./dbc-parse/dbc-xml-sql-parse.lisp \
./dbc-parse/dbc-xml-refs-parse.lisp \
./dbc-parse/dbc-xml-parse-sax.lisp
./dbc-time/date-localtime-utils.lisp \
./dbc-translate/dbc-french-dates.lisp \
./dbc-translate/dbc-french-numbers.lisp \
--language=lisp

###  ==============================
### EOF
